### ISSUE TITLE
クラス図を書く

### ISSUE THREAD

**Issue by willofhare** [aseruneko/diceforge-ai#27]
やってみたい人いませんか?僕は嫌です。

**Comment by aseruneko** [comment]
- [x] ファイルのコメントを修正して依存関係がわかりやすいようにする
- [x] クラス図を書くツールを定義する
- [x] クラス図を書く

**Comment by aseruneko** [comment]
クラス図はdraw.ioあたりがデファクトスタンダードかなと思います
